[theme]
primaryColor = "#e50914"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#e5e5e5"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
